name: Autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: first_test
        type: choice
        options:
          - first_test
          - second_test
          - all_tests

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Firefox
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: first_test
        if: "github.event.deployment.target == 'first_test'"
        run: pytest test/test_simple_button.py::test_simple_button
      - name: second_test
        if: "github.event.deployment.target == 'second_test'"
        run: pytest test/test_simple_button.py::test_simple_button_page_title
      - name: all_tests
        if: "github.event.deployment.target == 'all_tests'"
        run: pytest -v
