name: Autotests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: action/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Firefox
        run: sudo apt-get install firefox
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
